l1-origin: Use finalized block as upper limit for l1 origin
celo-org/optimism pull request #206
Opened 2024-07-30 15:54 UTC by palango

Resolves https://github.com/celo-org/optimism/issues/200

Implements usage of the finalized L1 block when on Celo (this is determined by checking the `Cel2` timestamp in the config).

When enabled the code requests the latest finalized block. This requires a small change to the `L1Blocks` interface.
If the finalized block is not higher than the current origin, return the current origin.

ℹ️ : We could also implement a new struct like `L1OriginSelector`, but the changes are so small that I don't think that makes a lot of sense right now.

2024-07-31 15:14 UTC, mcortesi commented
I think we should use a diff strategy here...

Not have a new L1OriginSelector or modify it... 

but have a different version of it's dependency `L1Blocks` interface..

currently, the sequencer (check driver.go) uses:

```
type confDepth struct {
	// everything fetched by hash is trusted already, so we implement those by embedding the fetcher
	derive.L1Fetcher
	l1Head func() eth.L1BlockRef
	depth  uint64
}

func NewConfDepth(depth uint64, l1Head func() eth.L1BlockRef, fetcher derive.L1Fetcher) *confDepth {
	return &confDepth{L1Fetcher: fetcher, l1Head: l1Head, depth: depth}
}

// L1BlockRefByNumber is used for L1 traversal and for finding a safe common point between the L2 engine and L1 chain.
// Any block numbers that are within confirmation depth of the L1 head are mocked to be "not found",
// effectively hiding the uncertain part of the L1 chain.
func (c *confDepth) L1BlockRefByNumber(ctx context.Context, num uint64) (eth.L1BlockRef, error) {
	// TODO: performance optimization: buffer the l1Unsafe, invalidate any reorged previous buffer content,
	// and instantly return the origin by number from the buffer if we can.

	// Don't apply the conf depth if l1Head is empty (as it is during the startup case before the l1State is initialized).
	l1Head := c.l1Head()
	if l1Head == (eth.L1BlockRef{}) {
		return c.L1Fetcher.L1BlockRefByNumber(ctx, num)
	}
	if num == 0 || c.depth == 0 || num+c.depth <= l1Head.Number {
		return c.L1Fetcher.L1BlockRefByNumber(ctx, num)
	}
	return eth.L1BlockRef{}, ethereum.NotFound
}
```

that only returns blocks by number IF they are of a certain DEPTH.

Instead, have an impl that ONLY returns blocks IF they are finalized.

2024-07-31 15:14 UTC, mcortesi requested changes
chech the issue comment

2024-07-31 15:14 UTC, mcortesi commented on op-node/rollup/driver/origin_selector.go
> +	if los.cfg.IsCelo() {
as we want to make code 'upstream mergeable', i woudl not depend on "is Celo" but on another type of cfg, similar to the Depth config that states 'onlyOnFinalized' or something like that

2024-08-01 11:24 UTC, palango commented on op-node/rollup/driver/origin_selector.go
> +	if los.cfg.IsCelo() {
Sketched the alternative approach in https://github.com/celo-org/optimism/pull/209

2024-08-07 09:27 UTC, closed without merging